name: Deploy React App to EC2 with Docker and Nginx

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          # Build Docker image for the React app with Nginx
          docker build -t vishnuenest/my-react-app .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push vishnuenest/my-react-app:latest

      - name: SSH into EC2 and deploy the app
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > aws_ssh_key.pem
          chmod 600 aws_ssh_key.pem
          eval "$(ssh-agent -s)"
          ssh-add aws_ssh_key.pem

          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Navigate to the workspace directory
            cd /home/ubuntu/workspace

            # Pull the Docker image from Docker Hub
            docker pull vishnuenest/my-react-app:latest

            # Stop and remove any running container
            docker stop react-app-container || true
            docker rm react-app-container || true

            # Run the React app inside a Docker container with Nginx
            docker run -d --name react-app-container -p 80:80 vishnuenest/my-react-app:latest

            # Restart Nginx to ensure it's serving the app
            sudo systemctl restart nginx

            echo "Deployment successful!"
            exit
          EOF
